var annotated =
[
    [ "ATFViewerMain", "classATFViewerMain.html", "classATFViewerMain" ],
    [ "ATFViewerMainGLSL", "classATFViewerMainGLSL.html", "classATFViewerMainGLSL" ],
    [ "BasicShaderProgram", "classBasicShaderProgram.html", "classBasicShaderProgram" ],
    [ "BitmapString", "classBitmapString.html", null ],
    [ "CountCrossing", "classCountCrossing.html", "classCountCrossing" ],
    [ "countCrossingDeviceTemp", "structcountCrossingDeviceTemp.html", null ],
    [ "countCrossingDeviceTemp< D, 1 >", "structcountCrossingDeviceTemp_3_01D_00_011_01_4.html", null ],
    [ "countCrossingHostTemp", "structcountCrossingHostTemp.html", null ],
    [ "countCrossingHostTemp< D, 1 >", "structcountCrossingHostTemp_3_01D_00_011_01_4.html", null ],
    [ "countCrossingTemp", "structcountCrossingTemp.html", null ],
    [ "countCrossingTemp< D, 1 >", "structcountCrossingTemp_3_01D_00_011_01_4.html", null ],
    [ "DBAccessor", "classDBAccessor.html", "classDBAccessor" ],
    [ "DeviceSeq", "classDeviceSeq.html", "classDeviceSeq" ],
    [ "DeviceSeqConst", "classDeviceSeqConst.html", "classDeviceSeqConst" ],
    [ "EstimateSpecResult", "structEstimateSpecResult.html", "structEstimateSpecResult" ],
    [ "Fixes", "classFixes.html", "classFixes" ],
    [ "id_time", "structid__time.html", "structid__time" ],
    [ "Joystick", "classJoystick.html", "classJoystick" ],
    [ "LongLatBase", "structLongLatBase.html", "structLongLatBase" ],
    [ "Map", "classMap.html", "classMap" ],
    [ "MapTransform", "classMapTransform.html", "classMapTransform" ],
    [ "MapVAO", "classMapVAO.html", "classMapVAO" ],
    [ "Path", "structPath.html", "structPath" ],
    [ "PathPoint", "structPathPoint.html", "structPathPoint" ],
    [ "Paths", "classPaths.html", "classPaths" ],
    [ "PathsVAO", "classPathsVAO.html", "classPathsVAO" ],
    [ "Sectors", "classSectors.html", "classSectors" ],
    [ "SectorsVAO", "classSectorsVAO.html", "classSectorsVAO" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "ShaderProgram", "classShaderProgram.html", "classShaderProgram" ],
    [ "TestCountCrossing", "classTestCountCrossing.html", "classTestCountCrossing" ],
    [ "TestThread", "classTestThread.html", "classTestThread" ],
    [ "TestThread_MemFunc", "classTestThread__MemFunc.html", "classTestThread__MemFunc" ],
    [ "TestThreadFunc", "structTestThreadFunc.html", "structTestThreadFunc" ],
    [ "TestUseThread", "classTestUseThread.html", "classTestUseThread" ],
    [ "TestVBO", "classTestVBO.html", "classTestVBO" ],
    [ "Texture2D", "classTexture2D.html", "classTexture2D" ],
    [ "TextureShaderProgram", "classTextureShaderProgram.html", "classTextureShaderProgram" ],
    [ "TimeManager", "classTimeManager.html", null ],
    [ "Timer", "classTimer.html", "classTimer" ],
    [ "TimeSeparation", "classTimeSeparation.html", "classTimeSeparation" ],
    [ "TrackDataManager", "classTrackDataManager.html", "classTrackDataManager" ],
    [ "UniformVariable", "classUniformVariable.html", "classUniformVariable" ],
    [ "Util", "classUtil.html", null ],
    [ "VAOBase", "classVAOBase.html", "classVAOBase" ],
    [ "VAOLayoutPaths", "classVAOLayoutPaths.html", "classVAOLayoutPaths" ],
    [ "VAOLayoutPositionColor", "classVAOLayoutPositionColor.html", "classVAOLayoutPositionColor" ],
    [ "VAOLayoutPositionTexture", "classVAOLayoutPositionTexture.html", "classVAOLayoutPositionTexture" ],
    [ "VAOPositionBase", "classVAOPositionBase.html", "classVAOPositionBase" ],
    [ "VAOPositionColorDynamic", "classVAOPositionColorDynamic.html", "classVAOPositionColorDynamic" ],
    [ "VAOPositionTexture", "classVAOPositionTexture.html", "classVAOPositionTexture" ],
    [ "VBOBase", "classVBOBase.html", "classVBOBase" ],
    [ "VBODynamicBase", "classVBODynamicBase.html", "classVBODynamicBase" ],
    [ "VBOElementStatic", "classVBOElementStatic.html", "classVBOElementStatic" ],
    [ "VBOStatic", "classVBOStatic.html", "classVBOStatic" ]
];